pipeline {
    agent any

    environment {
        SPLUNK_HEC_URL = 'https://127.0.0.1:8088/services/collector/event'
        SPLUNK_HEC_TOKEN = credentials('3366c860-b822-4ee9-8cfe-398871d88cc5')
        SPLUNK_INDEX = 'jenkinsgit_logs'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm // Jenkins handles repo checkout
            }
        }

        stage('Install Dependencies') {
            steps {
                // Use correct working dir if your Node app is in a subfolder
                bat "npm install"
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    def packageJson = readJSON file: 'package.json'
                    if (packageJson.scripts?.test) {
                        bat "npm test"
                    } else {
                        echo 'No test script defined in package.json'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "Deploying to production..."
                    bat """
                        curl -k -X POST "%SPLUNK_HEC_URL%" ^
                            -H "Authorization: Splunk %SPLUNK_HEC_TOKEN%" ^
                            -d "{\\"event\\": \\"Deployment Started\\", \\"sourcetype\\": \\"login_logs\\", \\"index\\": \\"%SPLUNK_INDEX%\\"}"
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
